//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLesson()
        {
            this.tblTeacherLessonMappings = new HashSet<tblTeacherLessonMapping>();
        }
    
        public int Id { get; set; }
        public string LessonName { get; set; }
        public int CollegeId { get; set; }
        public int Unit { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeacherLessonMapping> tblTeacherLessonMappings { get; set; }
    }
}
