//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhotoToMessage
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int PhotoId { get; set; }
    
        public virtual tblMessage tblMessage { get; set; }
        public virtual tblPhoto tblPhoto { get; set; }
    }
}
