//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresenceAbsence
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int ClassRoomId { get; set; }
        public int SessionNumber { get; set; }
        public bool IsPresent { get; set; }
    
        public virtual tblTeacherLessonMapping tblTeacherLessonMapping { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
