//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestAnswer
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int Answer { get; set; }
        public string Description { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblRequest tblRequest { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
