//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleAccess
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int SystemPartId { get; set; }
    
        public virtual tblRole tblRole { get; set; }
        public virtual tblSystemPartName tblSystemPartName { get; set; }
    }
}
