//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRequest()
        {
            this.tblRequestAnswers = new HashSet<tblRequestAnswer>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RequestType { get; set; }
        public string RequestDetail { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<int> FileId { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<int> ScoreId { get; set; }
    
        public virtual tblPhoto tblPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestAnswer> tblRequestAnswers { get; set; }
        public virtual tblScore tblScore { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
