//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblScore()
        {
            this.tblRequests = new HashSet<tblRequest>();
        }
    
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int ClassRoomId { get; set; }
        public string Score { get; set; }
        public int Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequest> tblRequests { get; set; }
        public virtual tblTeacherLessonMapping tblTeacherLessonMapping { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
