//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentClassroomMapping
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int ClassroomId { get; set; }
        public Nullable<bool> IsPassed { get; set; }
    
        public virtual tblTeacherLessonMapping tblTeacherLessonMapping { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
