//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeacherLessonMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeacherLessonMapping()
        {
            this.tblPresenceAbsences = new HashSet<tblPresenceAbsence>();
            this.tblScores = new HashSet<tblScore>();
            this.tblStudentClassroomMappings = new HashSet<tblStudentClassroomMapping>();
        }
    
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int LessonId { get; set; }
        public int Year { get; set; }
        public int Term { get; set; }
        public int Capacity { get; set; }
        public int CollegeId { get; set; }
        public int Remain { get; set; }
        public int Taken { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public Nullable<int> Day { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        public virtual tblLesson tblLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPresenceAbsence> tblPresenceAbsences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblScore> tblScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentClassroomMapping> tblStudentClassroomMappings { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
