//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblExtraAccesses = new HashSet<tblExtraAccess>();
            this.tblLogings = new HashSet<tblLoging>();
            this.tblMessages = new HashSet<tblMessage>();
            this.tblMessages1 = new HashSet<tblMessage>();
            this.tblPresenceAbsences = new HashSet<tblPresenceAbsence>();
            this.tblRequestAnswers = new HashSet<tblRequestAnswer>();
            this.tblRequests = new HashSet<tblRequest>();
            this.tblRoleToUsers = new HashSet<tblRoleToUser>();
            this.tblScores = new HashSet<tblScore>();
            this.tblStudentClassroomMappings = new HashSet<tblStudentClassroomMapping>();
            this.tblTeacherLessonMappings = new HashSet<tblTeacherLessonMapping>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string FathersName { get; set; }
        public int GenderId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Educational_Field_Id { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public bool IsPay { get; set; }
        public Nullable<int> PhotoId { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        public virtual tblEducationalField tblEducationalField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExtraAccess> tblExtraAccesses { get; set; }
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoging> tblLogings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessage> tblMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessage> tblMessages1 { get; set; }
        public virtual tblPhoto tblPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPresenceAbsence> tblPresenceAbsences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestAnswer> tblRequestAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequest> tblRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoleToUser> tblRoleToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblScore> tblScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentClassroomMapping> tblStudentClassroomMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeacherLessonMapping> tblTeacherLessonMappings { get; set; }
    }
}
