//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserLoging
    {
        public string RoleTitle { get; set; }
        public System.DateTime LoginDatetime { get; set; }
        public Nullable<System.DateTime> LogoutDatetime { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string FathersName { get; set; }
        public string GenderTitle { get; set; }
        public string PhoneNumber { get; set; }
        public string Educational_Field { get; set; }
        public string CollegeName { get; set; }
        public string PhotoAddress { get; set; }
    }
}
