//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_VideoToMessage
    {
        public int MessageId { get; set; }
        public int VideoId { get; set; }
        public string VideoName { get; set; }
        public string VideoSuffix { get; set; }
        public string VideoAddress { get; set; }
    }
}
