//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PhotoToMessage
    {
        public int PhotoId { get; set; }
        public int MessageId { get; set; }
        public string PhotoName { get; set; }
        public string PhotoSuffix { get; set; }
        public string PhotoAddress { get; set; }
    }
}
