//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Message
    {
        public int MessageId { get; set; }
        public int SenderId { get; set; }
        public string SenderUserName { get; set; }
        public string SenderFirstName { get; set; }
        public string SenderLastName { get; set; }
        public string SenderGender { get; set; }
        public string SenderPhotoAddress { get; set; }
        public int ReceiverId { get; set; }
        public string ReceiverUserName { get; set; }
        public string ReceiverFirstName { get; set; }
        public string ReceiverLastName { get; set; }
        public string ReceiverGender { get; set; }
        public string ReceiverPhotoAddress { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> ReplyTo { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsRead { get; set; }
    }
}
