//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Score
    {
        public int ClassroomId { get; set; }
        public int StudentId { get; set; }
        public string StudentUserName { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentNationalCode { get; set; }
        public string StudentGender { get; set; }
        public string StudentEducationalField { get; set; }
        public string StudentPhotoAddress { get; set; }
        public int TeacherId { get; set; }
        public string TeacherNationalCode { get; set; }
        public int LessonId { get; set; }
        public string LessonName { get; set; }
        public int CollegeId { get; set; }
        public string CollegeName { get; set; }
        public int Year { get; set; }
        public int Term { get; set; }
        public string TeacherUserName { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public int Unit { get; set; }
        public bool IsActive { get; set; }
        public string Score { get; set; }
        public int Type { get; set; }
        public int ScoreId { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
    }
}
