//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Requests
    {
        public int RequesterId { get; set; }
        public string RequesterUserName { get; set; }
        public string RequesterFirstName { get; set; }
        public string RequesterLastName { get; set; }
        public int RequestType { get; set; }
        public string RequestDetail { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<int> Answer { get; set; }
        public string AnswerDetail { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeUserName { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string TeacherUserName { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public string LessonName { get; set; }
        public Nullable<int> ClassroomId { get; set; }
        public string Score { get; set; }
        public Nullable<int> ScoreType { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> FileId { get; set; }
        public int RequestId { get; set; }
        public string FileAddress { get; set; }
        public string FileName { get; set; }
        public string FileSuffix { get; set; }
        public Nullable<int> FileType { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public Nullable<int> ScoreId { get; set; }
        public string RequesterGender { get; set; }
        public string RequesterPhotoAddress { get; set; }
    }
}
