//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserRoles
    {
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RoleTitle { get; set; }
        public string UserName { get; set; }
        public string RoleEnglishName { get; set; }
    }
}
