//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ClassRoom
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int LessonId { get; set; }
        public string LessonName { get; set; }
        public int CollegeId { get; set; }
        public string CollegeName { get; set; }
        public int Capacity { get; set; }
        public int Remain { get; set; }
        public int Taken { get; set; }
        public int Year { get; set; }
        public int Term { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public int Unit { get; set; }
        public bool IsActive { get; set; }
        public string CollegeEnglishName { get; set; }
        public string TeacherUserName { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherGender { get; set; }
        public string TeacherNationalCode { get; set; }
        public string TeacherPhotoAddress { get; set; }
    }
}
